### ISSUE TITLE
Deterministic keys

### ISSUE THREAD

**Issue by av-hr** [ctrlsa/smart-contract-wallet-Ethereum-Account-Abstraction-Telegram#12]

**Comment by thuan2172001** [comment]
### Add Deterministic Keys Feature to Telegram Mini Apps  

#### Checklist:  

- [ ] **Research Deterministic Keys Integration**  
  - Investigate deterministic key derivation methods (e.g., BIP-32, BIP-44).  
  - Analyze constraints for using deterministic keys in Telegram Mini Apps.  

- [ ] **Implement Key Derivation & Signing**  
  - Develop a module for deterministic key derivation and management.  
  - Implement transaction signing for Ethereum using deterministic keys.  

- [ ] **Prototype Mini App**  
  - Build a basic Mini App demonstrating transaction signing with deterministic keys.  

- [ ] **Document Solution**  
  - Write a README file summarizing the implementation.  
  - Include diagrams and integration notes as required.  

---

#### Output:  
- Code  
- Architecture diagram  
- README file  

#### Contributor:  
Leo  

#### Start Date:  
16.11.2024  

#### Delivery Date:  
30.11.2024
