### ISSUE TITLE
 Integrate Rabby wallet solutions in Telegram Mini App

### ISSUE THREAD

**Issue by DS-jr** [ctrlsa/smart-contract-wallet-Ethereum-Account-Abstraction-Telegram#38]
https://rabby.io/ 

https://rabbykit.rabby.io/ 

https://rabbykit.rabby.io/docs/introduction 

https://rabby.io/docs/integrating-rabby-wallet/

**Comment by Agastya18** [comment]
i want to try it @DS-jr

**Comment by DS-jr** [comment]
Hi @Agastya18 ! 

Thank you for offering to help - 💪

Please, check "How to contribute" section in ReadMe:
https://github.com/ctrlsa/smart-contract-wallet-Ethereum-Account-Abstraction-Telegram?tab=readme-ov-file#how-to-contribute
